# Generated by Django 4.2.8 on 2023-12-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camanagement', '0003_rtsprecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='camanagement.rtsprecording')),
            ],
        ),
    ]
