# Generated by Django 4.2.8 on 2024-03-10 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rtsp_url', models.URLField(max_length=1000)),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='RTSPRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('bitrate', models.PositiveIntegerField()),
                ('quality', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51)])),
                ('duration', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(21)])),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camanagement.camera')),
            ],
        ),
        migrations.CreateModel(
            name='HLSTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,5}x\\d{1,5}')])),
                ('bitrate', models.PositiveIntegerField()),
                ('quality', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51)])),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camanagement.camera')),
            ],
        ),
    ]
