# Generated by Django 4.2.8 on 2023-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(max_length=1000),
        ),
    ]
