# Generated by Django 4.2.8 on 2023-12-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camanagement', '0002_alter_camera_rtsp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSPRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camanagement.camera')),
            ],
        ),
    ]
